baseURL                        = "https://dadlan.com/"
copyright                      = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
defaultContentLanguage         = "en"
defaultContentLanguageInSubdir = true
enableEmoji                    = true
enableGitInfo                  = true
languageCode                   = "en-us"
pygmentsCodefences             = true
pygmentsUseClasses             = true
rssLimit                       = 10
theme                          = "hermit-v2"
title                          = "dadlan"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block  = [['$$', '$$'], ['\[', '\]']] # Mathjax support
          inline = [['\(', '\)']]               # Mathjax support

[params.author]
  name = "DadLAN"

[params]
bgImg               = "/images/dadlan-fall-2018-oldphoto.jpg"          # Homepage background-image URL
code_copy_button    = true
dateform            = "Jan 2, 2006"
dateformNum         = "2006-01-02"
dateformNumTime     = "2006-01-02 15:04 -0700"
dateformShort       = "Jan 2"
description         = "dadlan usa"
descriptionInPosts  = true
footerCopyright     = ' &#183;'
gitUrl              = "https://github.com/dadlan/dadlan.com/tree/main"
global_mathjax      = false
homeSubtitle        = ""
homeSubtitlePrinter = true
justifyContent      = false                                            # Set "text-align: justify" to .content.
pinned              = "Pinned Posts"
pinnedSVGname       = "pin"
readTime            = true
readTimeSeparator   = ":"
relatedPosts        = true
scrollToTop         = true
shareSocial         = true
themeColor          = "#494f5c"

  [[params.socialLinks]]
    name = "github"
    url  = "https://github.com/dadlan"


[menu]
  [[menu.main]]
    name   = "Posts"
    url    = "posts/"
    weight = 10

  [[menu.main]]
    name   = "About"
    url    = "about/"
    weight = 20
