name: github pages

on:
  pull_request:
    types:
      - opened
      - edited
  push:
    branches:
      - master

jobs:
  build-deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true
      - name: build
        uses: mattbailey/actions-hugo@v0.105.0
        if: github.event.deleted == false
        with:
          args: --gc --minify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
